[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["vnomarrow <vnomarrow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
trait_enum = "0.5.0"
